//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sistema_Fallas_IMSS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class foro_soluciones
    {
        public int Id_solucion { get; set; }
        public string problema { get; set; }
        public string solucion { get; set; }
        public string autor { get; set; }
        public string correo { get; set; }
        public string titulo { get; set; }
    }
}
